print:
  target:
    entity:
      integration: memobird_local
      domain: notify
  fields:
    message:
      required: true
      example: "Купить молоко"
      selector:
        text:
          multiline: true
    format:
      selector:
        select:
          options:
            - plain
            - markdown
            - html
          translation_key: format
    title:
      example: "Список покупок"
      selector:
        text:
    big:
      default: false
      selector:
        boolean:
    bold:
      default: false
      selector:
        boolean:
    underline:
      default: false
      selector:
        boolean:
    timestamp:
      default: true
      selector:
        boolean:
    separator:
      default: true
      selector:
        boolean:
print_image:
  target:
    entity:
      integration: memobird_local
      domain: notify
  fields:
    file:
      example: "/config/www/photo.jpg"
      selector:
        text:
    url:
      example: "https://example.com/image.png"
      selector:
        text:
          type: url
    camera:
      selector:
        entity:
          domain: camera
    title:
      selector:
        text:
    caption:
      selector:
        text:
          multiline: true
    format:
      selector:
        select:
          options:
            - plain
            - markdown
            - html
          translation_key: format
    dither:
      default: true
      selector:
        boolean:
    timestamp:
      default: false
      selector:
        boolean:
    separator:
      default: true
      selector:
        boolean:
